### ISSUE TITLE
make it copatible with aws service codes and servce names

### ISSUE THREAD

**Issue by amanenk** [burib/aws-region-table-parser#22]
I have a use case where I need to check if my error is related to a networking or service is just not available in requested region. I have a domain name that is requested but in case of cognito requests domain name is one of `cognito-identity`, `cognito-idp` or `cognito-sync`. It would awesome to match `cognito` service from `parseddata.json` with service codes above. 
There is a command to list all the service names and service codes `aws service-quotas list-services`
The part of response looks next:
```
        {
            "ServiceCode": "cognito-identity",
            "ServiceName": "Amazon Cognito Federated Identities"
        },
        {
            "ServiceCode": "cognito-idp",
            "ServiceName": "Amazon Cognito User Pools"
        },
        {
            "ServiceCode": "cognito-sync",
            "ServiceName": "Amazon Cognito Sync"
        },
```

**Comment by burib** [comment]
@amanenk thanks for the feedback and the idea, it's really valuable. I can take a look at the implementation next week.

**Comment by burib** [comment]
@amanenk I think I've fixed what you meant.

Now I'm using the service code as an index, instead of parsing the url. ( for example: https://github.com/burib/aws-region-table-parser/blob/master/data/parseddata.json#L3167 )

This way you can query the `aws service-quotas list-services` by the service code.

does it fixes your problem ?

**Comment by burib** [comment]
also, sorry for the late response.
